### ISSUE TITLE
TP 03 est OK, mais ...

### ISSUE THREAD

**Issue by JeffAbrahamson** [AlexDesvallees/Alex-ML#4]
C'est très bien que tout est OK, mais peut-être tu pourrais indiquer la signification de tout ça ?

**Comment by AlexDesvallees** [comment]
Ajouts de commentaires, on notera que je n'ai pas fait les classifieurs pour les classes au-delà de 1 (donc de 2 à 9).
Egalement, il manque la partie One vs Rest que je n'ai pas bien compris dans le code malgré les explications de Nicolas donc c'est pour cela que c'est en commentaire dans le code...
